services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DATABASE_NAME: dev_database
      PGPRORT: 15432
    ports:
      - "15432:15432"
    command: -p 15432
